analyzer:
  errors:
    one_member_abstracts: ignore
    avoid_catching_errors: ignore
include: package:very_good_analysis/analysis_options.6.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
