name: vgv_challenge
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  get_it: ^8.0.3
  hive: ^2.2.3
  intl: ^0.19.0
  path: ^1.9.0
  path_provider: ^2.1.5
  shimmer: ^3.0.0
  uuid: ^4.5.1

dev_dependencies:
  bloc_test: ^9.1.7
  faker: ^2.2.0
  flutter_test:
    sdk: flutter
  hive_test: ^1.0.1
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
